# ==============================================================
# WAX CONFIGURATION
# ==============================================================
# Jekyll configuration files are written in YAML format.
# Colons, tabs/spacing, and quotes are meaningful in YAML.
# It is recommended you look at the following guide to avoid
# syntax errors in this file:
# ~> https://learnxinyminutes.com/docs/yaml/
#
#
# Questions ?
# ~> https://minicomp.github.io/wiki/#/
#
# ---------------------------------------------------------------
# MAIN SETTINGS
# ---------------------------------------------------------------
# Feel free to change these! For more info, refer to:
# ~> https://jekyllrb.com/docs/configuration/options/

title:            'Arabic Renaissance Sculpture'
description:      'an exhibition of historical photographs from the Kunsthistorisches Insitut in Florence'
url:              'https://rutgersdh.github.io'
baseurl:          '/ars'
copyright:        '2025'
logo:             '/img/bildmarke-khi.png'
default_thumb:    '/assets/default.png'

# ---------------------------------------------------------------
# BUILD SETTINGS
# ---------------------------------------------------------------
# Best not to mess with these unless you know what you're doing!

permalink: 'pretty'
sass:
  style: compressed
exclude: ["Gemfile*", "*.gemspec", "Rakefile", "vendor", "spec", "README.md", "LICENSE.txt", "Docker*"]
webrick:
  headers:
    'Access-Control-Allow-Origin': '*'
kramdown:
 auto_ids:       true
 footnote_nr:    1
 entity_output:  as_char
 footnote_backlink: "&#x21a9;&#xfe0e;"
 toc_levels:     1..6
 smart_quotes:   lsquo,rsquo,ldquo,rdquo
 enable_coderay: false


# --------------------------------------------------------------
# COLLECTION SETTINGS
# --------------------------------------------------------------
# Wax leverages Jekyll collections for much of its
# functionality, therefor some of the keys below are from
# Jekyll while others are Wax-specific.
# For more info, refer to:
# ~> https://jekyllrb.com/docs/collections/

collections:
  exhibits:
    output: true
  ars: # name of collection
    output: true # makes sure pages are output as html files
    layout: 'ars_item' # the layout for the pages to use
    metadata:
      source: 'ars.csv' # path to the metadata file within `_data`
    images:
      source: 'raw_images/ars' # path to the directory of images within `_data`

# --------------------------------------------------------------
# SEARCH INDEX SETTINGS
# --------------------------------------------------------------
# You can create multiple search indexes below (though only one is
# recommended!) by specifying
# an `index` file to write it to and some `collections` for it to index
# and running `$ bundle exec rake wax:search` .

search:
  main:
    index: '/search/index.json' # file the index will get written to
    collections:
      ars:
        content: false # whether or not to index page content
        fields: # the metadata fields to index
          - artist
          - title
          - location
          - photographer
          - type_of_photo
          - category
          - entry_year

# --------------------------------------------------------------
# SITE MENU SETTINGS
# --------------------------------------------------------------
# Each menu item needs a `label` (whats shown), and a `link`
# (where it goes). An item can optionally have a dropdown
# submenu via `sub`.

menu:
  - label: 'Exhibits'
    sub:
      - label: 'Inline Parallax Image'
        link: '/exhibits/a/'
      - label: 'Inline Image References'
        link: '/exhibits/b/'
  - label: 'Browse'
    link: '/collection/'
  - label: 'Search'
    link: '/search/'

# --------------------------------------------------------------
# SITE FOOTER SETTINGS
# --------------------------------------------------------------
#

footer:
  links:
    - label: 'GitHub'
      link: 'https://github.com/rutgersdh/ars'
    - label: 'Contact'
      link: 'mailto:alex.seggerman@rutgers.edu'
  logos:
    - img: '/img/bildmarke-khi.png'
      link: 'https://www.khi.fi.it/'
    - img: '/img/RLIB_V_WHITE_BLACK_RGB.png'
      link: 'https://www.libraries.rutgers.edu/'

# FIN
